name: Auto-Release on Tag

on:
  push:
    tags:
      - 'v*' # Der Bot startet, sobald du einen Tag pushst, der mit 'v' beginnt (v1.0, v1.1.2 etc.)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update module.json
        run: |
          node << 'EOF'
          const fs = require('fs');
          const manifest = JSON.parse(fs.readFileSync('module.json', 'utf8'));
          const version = "${{ steps.get_version.outputs.VERSION }}".replace('v', '');
          
          manifest.version = version;
          manifest.url = "https://github.com/blubbedi/bg3-dialogue-system";
          manifest.manifest = `https://github.com/blubbedi/bg3-dialogue-system/releases/latest/download/module.json`;
          manifest.download = `https://github.com/blubbedi/bg3-dialogue-system/releases/download/${{ steps.get_version.outputs.VERSION }}/module.zip`;
          
          fs.writeFileSync('module.json', JSON.stringify(manifest, null, 2));
          EOF

      - name: Zip Files
        run: zip -r ./module.zip module.json scripts styles templates README.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            module.json
            module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}